run: part1
	./part1

run2: part2
	./part2

part1:
	~/Downloads/x10-2.6.2_macosx_x86_64/bin/x10c++ -o part1 Part1.x10

part2:
	~/Downloads/x10-2.6.2_macosx_x86_64/bin/x10c++ -o part2 Part2.x10

clean:
	rm *.cc *.h part1 part2; true